#!/bin/sh
set -e

case "$1" in
    configure)
        # Update icon cache if gtk-update-icon-cache is available.
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -q /usr/share/icons/hicolor || true
        fi
        ;;
esac

#DEBHELPER#
