#!/bin/sh
set -e

case "$1" in
    remove|purge)
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -q /usr/share/icons/hicolor || true
        fi
        ;;
esac

#DEBHELPER#
